import pandas as pd
import ta
from agents.base_agent import BaseAgent

class TechnicalAnalysisAgent(BaseAgent):
    def __init__(self, name: str = "TechnicalAnalysis"):
        super().__init__(name)

    def process(self, df: pd.DataFrame):
        """
        Adds technical indicators to the DataFrame.
        """
        if df is None or df.empty:
            self.logger.warning("Received empty DataFrame")
            return None

        self.logger.info("Computing technical indicators...")
        df = df.copy()

        # Add RSI
        df['rsi'] = ta.momentum.RSIIndicator(close=df['close'], window=14).rsi()

        # Add MACD
        macd = ta.trend.MACD(close=df['close'])
        df['macd'] = macd.macd()
        df['macd_signal'] = macd.macd_signal()
        df['macd_diff'] = macd.macd_diff()

        # Add SMA
        df['sma_20'] = ta.trend.SMAIndicator(close=df['close'], window=20).sma_indicator()
        df['sma_50'] = ta.trend.SMAIndicator(close=df['close'], window=50).sma_indicator()

        # Drop NaN values generated by indicators
        df.dropna(inplace=True)
        
        return df
